repos:
  - repo: https://github.com/awslabs/git-secrets
    rev: v1.4.3
    hooks:
      - id: git-secrets

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: detect-aws-credentials
      - id: detect-private-key
      - id: check-json
      - id: check-yaml
      
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
     - id: detect-secrets

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.4  
    hooks:
      - id: bandit
        args: ['--severity-level', 'high']


