# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

	#trusty64 https://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-amd64-vagrant-disk1.box
	#debian7 http://puppet-vagrant-boxes.puppetlabs.com/debian-73-x64-virtualbox-nocm.box

	config.vm.box = "trusty64"

	config.vm.define :cacti do |cacti_config|
		cacti_config.vm.network :private_network, :ip => "192.169.0.10"
	end

	config.vm.define :web do |web_config|
		web_config.vm.box = "debian7"
		web_config.vm.network :private_network, :ip => "192.169.0.11"
	end

	config.vm.define :db do |db_config|
		db_config.vm.network :private_network, :ip => "192.169.0.12"
	end  

end
